### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by dili021** [dili021/Web-Dev-School#5]

**Comment by Kyle-Law** [comment]
Great Job @dili021 ! I didn't see the footer problem but here are few I got from my screen:
![image](https://user-images.githubusercontent.com/55923773/74632014-5f5d0800-5199-11ea-8939-baa5f12ebf5b.png)

The logo/images are not shown properly. Have you uploaded/specified correctly the file name?

**Comment by patriciachrysy** [comment]
Good job @dili021 !!!!
I saw the problem with your footer. I just had to remove position absolute and bottom and it fixed it
